[package]
name = "mirage"
version = "0.1.0"
edition = "2021"
description = "Image processing application"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
image = "0.25.1"
num-complex = "0.4.2"
